steps:
  # 1. Install zip package in an Ubuntu container
  - name: ubuntu
    entrypoint: bash
    args:
      - "-c"
      - "apt-get update && apt-get install -y zip && zip -r /workspace/function.zip ."

  # 2. Upload function code to GCS
  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "/workspace/function.zip", "gs://bucketinteli/my-function-code.zip"]

  # 3. Deploy Cloud Function from GCS
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - gcloud
      - functions
      - deploy
      - my-cloud-function
      - --region=us-central1
      - --source=gs://bucketinteli/my-function-code.zip
      - --entry-point=myFunctionHandler
      - --runtime=nodejs20
      - --trigger-http
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 600s
