steps:
  # 1. Install zip package
  - name: gcr.io/cloud-builders/bash
    script: |
      apt-get update && apt-get install -y zip

  # 2. Compress the function code manually
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - "-c"
      - "zip -r function.zip ."

  # 3. Upload function code to GCS
  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "function.zip", "gs://my-functions-bucket/my-function-code.zip"]

  # 4. Deploy Cloud Function from GCS
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - gcloud
      - functions
      - deploy
      - my-cloud-function
      - --region=us-central1
      - --source=gs://my-functions-bucket/my-function-code.zip
      - --entry-point=myFunctionHandler
      - --runtime=nodejs20
      - --trigger-http
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 600s
